package spiralcraft.text.markup;

/**
 * A consumer of markup units generated by the MarkupParser
 */
public interface MarkupHandler
{
  void handleContent(CharSequence text);
  
  void handleMarkup(CharSequence code)
    throws Exception;
}
